---
project:
  type: website
  title: "Aleksanders Website"
  output-dir: docs
  preview:
    port: 4200
    browser: false

lang: da

# filters:
#   - auto-dark

website:
  title: "Aleksander Bang-Larsen"
  description: "Aleksander Bang-Larsens hjemmeside, hvor du kan finde guides og andet"
  # draft-mode: unlinked
  navbar:
    background: $background-color
    right:
      - href: index.qmd
        text: Forside
        icon: house-door-fill
      - guides.qmd
      # - href: https://cv.aleksanderbl.dk
      #   text: CV
      #   icon: file-earmark-person-fill
      #   target: _blank
      - href: cv.qmd
        # text: Quarto CV
        text: CV
      - rpkg.qmd
      - text: Kontakt mig
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/aleksanderbl
            target: _blank
          - icon: envelope
            text: E-Mail
            href: mailto:hej@aleksanderbl.dk
      - icon: github
        href: https://github.com/aleksanderbl29/aleksanderbldk
        target: _blank
      - icon: rss
        href: guides.xml
  page-footer:
    background: light
    left: © Copyright 2024, Aleksander Bang-Larsen
    right: Denne side er bygget med [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/aleksanderbl29/aleksanderbldk){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} og [Quarto](https://quarto.org/){target=_blank}

  repo-actions: []
  repo-url: https://github.com/aleksanderbl29/aleksanderbl29.github.io
  repo-link-target: _blank
  site-url: https://aleksanderbl.dk
  open-graph: true

  # reader-mode: true

format:
  html:
    theme:
      - cosmo
      - styles.css
    toc: true
    smooth-scroll: true
