---
title: Aleksander Bang-Larsen
subtitle: Curriculum Vitae
email: cv@aleksanderbl.dk
telephone: 42521513
homepage: aleksanderbl.dk
github: aleksanderbl29
fontfamily: libertine
monofont: inconsolata
spacing: onehalf
format:
  html: default
  pdf:
    template: cv-template.latex
other-links:
  - text: Send mig en mail!
    icon: envelope
    href: mailto:cv@aleksanderbl.dk
  - text: LinkedIn
    icon: linkedin
    href: https://linkedin.com/in/aleksanderbl
    target: _blank
  - text: Github
    icon: github
    href: https://github.com/aleksanderbl29
    target: _blank
---

# Om mig

Jeg er statskundsksabsstuderende med en stor interesse for kvantitative metoder og vælgeradfærd.

Udover mine studier bruger jeg meget tid på at lære nye ting, og jeg har viden indenfor mange teknologiske emner.

# Uddannelse

## 2021 til 2026 --- Statskundskab v. Aarhus Universitet

### Kandidat --- 2024 til 2026

Jeg er i gang med min kandidat i statskundskab på Aarhus Universitet. Her har jeg stort fokus på kvantitative metoder, analyser og visualiseringer samt datascience i politisk kontekst.

### Bachelor --- 2021 til 2024

Jeg færdiggjorde i sommeren 2024 min bachelor i statskundskab på Aarhus Universitet. Her havde jeg valgfag om vælgeradfærd og skrev min bacheloropgave i vælgeradfærd og politisk repræsentation. I min bacheloropgave undersøgte jeg spørgsmålet: *Hvordan er vælgernes elektorale reaktion på opførslen af vindmøller i lokalområdet*.

## 2017 til 2020 --- Studentereksamen fra Herning Gymnasium

Jeg har min studentereksamen fra Herning Gymnasium. Her havde jeg en samfundssproglig studieretning med samfundsfag A, engelsk A og fransk A som hovedfag.

# Erfaring

## 2023 til nu --- Underviser i Excel og VBA hos Djøf

Underviser i Excel og VBA for Djøf Studerende, hvor jeg underviser medlemmer af Djøf Studerende i Excel på fire kursusniveauer samt VBA på to niveauer.
Her har jeg udviklet mine undervisningskompetencer og er komfortabel med præsentation foran store mængder.

## 2021 til 2023 --- Student Assistant hos EG A/S

Ansat som studentermedhjælper i først kreditor-bogholderiet, og derefter debitor-bogholderiet, i IT-virksomheden EG, hvor jeg indtil studiestart i september 2021 arbejdede fuldtid og herefter deltid ved siden af studiet. Jeg håndterede varierende bogholderi-opgaver i Excel, ERP-systemet NetSuite samt lønningssystemet Zalaris.

## 2020 til 2021 --- Video Editor og ansvarlig for webshops hos Gigantic ApS

I de første 4 måneder af min ansættelse var mine primære opgaver at redigere reklame-indhold til sociale medier for diverse webshops i virksomheden i Shopify. Herefter fik jeg ansvaret for et af virksomhedens webshop-brands, hvor jeg styrede webshops i Danmark, Sverige, Norge og Finland.

::: {.content-visible when-format="html"}

# Kompetencer

```{r, dev = "png", dev.args=list(bg="transparent")}
#| echo: false
#| warning: false
#| fig-width: 10
#| fig-height: 3
library(tidyverse)

skills <- list(R = 90, Excel = 87, Git = 70, VBA = 60, LaTeX = 50)
sorted_names <- names(sort(unlist(skills), decreasing = FALSE))

tibble(skill = names(skills),
       level = unlist(skills)) |> 
  mutate(level = level / 100) |> 
  ggplot(aes(x = reorder(skill, level), y = level)) +
  geom_col(fill = "#98D8B0", width = 0.7) +
  annotate("text", x = seq(1, length(skills)), y = 0.025, label = sorted_names,
           hjust = 0, size = 5, color = "black") +
  coord_flip() +
  theme_void()
```

:::


